import { Settings, Key, Video, Shield } from "lucide-react";
import { ChecklistItem, CategoryInfo } from "../types";

export const facebookChecklistItems: ChecklistItem[] = [
  // App Setup
  {
    id: "facebook_dev_app",
    title: "Facebook Developer App Created",
    description: "Application registered in Meta Developer Portal with correct app type.",
    category: "setup",
    link: "https://developers.facebook.com/apps/",
    required: true,
    notes: "✅ Created (App ID: 1595929598380559)",
  },
  {
    id: "facebook_app_id_secret",
    title: "App ID and Secret Configured",
    description: "Facebook App ID and App Secret stored securely in environment variables.",
    category: "setup",
    required: true,
    notes: "✅ Configured",
  },
  {
    id: "facebook_redirect_uri",
    title: "OAuth Redirect URI Configured",
    description: "Valid OAuth redirect URI added in Facebook app settings.",
    category: "setup",
    required: true,
    notes: "✅ Configured",
  },
  {
    id: "facebook_business_verification",
    title: "Business Verification (if required)",
    description: "Complete business verification for access to certain permissions.",
    category: "setup",
    link: "https://developers.facebook.com/docs/development/release/business-verification",
    required: false,
  },
  // Permissions
  {
    id: "facebook_public_profile",
    title: "public_profile Advanced Access",
    description: "Advanced Access for public_profile permission granted by Meta.",
    category: "permissions",
    required: true,
    notes: "✅ Granted — Mar 9, 2026",
  },
  {
    id: "facebook_pages_show_list",
    title: "pages_show_list Advanced Access",
    description: "Advanced Access for pages_show_list permission granted by Meta.",
    category: "permissions",
    required: true,
    notes: "✅ Granted previously",
  },
  {
    id: "facebook_pages_read",
    title: "pages_read_engagement Permission",
    description: "Read engagement data from Pages managed by the user.",
    category: "permissions",
    required: true,
  },
  {
    id: "facebook_pages_manage",
    title: "pages_manage_posts Permission",
    description: "Create, edit and delete posts on Pages managed by the user.",
    category: "permissions",
    link: "https://developers.facebook.com/docs/permissions/reference/pages_manage_posts",
    required: true,
    notes: "⏳ Submit after Request button activates (~24h)",
  },
  {
    id: "facebook_pages_manage_engagement",
    title: "pages_manage_engagement Permission",
    description: "Required for posting first comments on Page posts.",
    category: "permissions",
    link: "https://developers.facebook.com/docs/permissions/reference/pages_manage_engagement",
    required: true,
    notes: "⏳ Added to OAuth scopes — needs App Review for Advanced Access",
  },
  {
    id: "facebook_publish_video",
    title: "publish_video Permission (for Reels)",
    description: "Required for publishing video content including Reels.",
    category: "permissions",
    required: false,
  },
  {
    id: "facebook_business_management",
    title: "business_management Permission",
    description: "Access to manage business assets if using Business Manager.",
    category: "permissions",
    required: false,
  },
  // Content Requirements
  {
    id: "facebook_image_specs",
    title: "Image Specifications",
    description: "Images: JPEG or PNG, min 200x200px, max 8MB for posts.",
    category: "content",
    link: "https://developers.facebook.com/docs/graph-api/reference/page/photos/",
    required: true,
  },
  {
    id: "facebook_video_specs",
    title: "Video Specifications",
    description: "Videos: MP4 or MOV, max 10GB, up to 240 minutes duration.",
    category: "content",
    link: "https://developers.facebook.com/docs/video-api/guides/publishing",
    required: true,
  },
  {
    id: "facebook_reels_specs",
    title: "Reels Specifications",
    description: "Reels: 9:16 aspect ratio, 3-90 seconds, under 1GB.",
    category: "content",
    link: "https://developers.facebook.com/docs/video-api/guides/reels-publishing",
    required: false,
  },
  {
    id: "facebook_page_selection",
    title: "Page Selection UI",
    description: "Allow users to select which Page to post to from connected Pages.",
    category: "content",
    required: true,
  },
  {
    id: "facebook_test_post",
    title: "Successful Test Post from Postora",
    description: "Published a real post to Facebook Page via Postora to register API calls.",
    category: "content",
    required: true,
    notes: "✅ Published successfully — Mar 9, 2026 (Daressny page)",
  },
  // Compliance
  {
    id: "facebook_privacy_policy",
    title: "Privacy Policy URL",
    description: "Privacy policy URL added to Facebook app settings.",
    category: "compliance",
    internalLink: "/privacy",
    required: true,
    notes: "✅ Configured",
  },
  {
    id: "facebook_tos_url",
    title: "Terms of Service URL",
    description: "Terms of service URL configured in app settings.",
    category: "compliance",
    internalLink: "/terms",
    required: true,
    notes: "✅ Configured",
  },
  {
    id: "facebook_platform_terms",
    title: "Meta Platform Terms Compliance",
    description: "Application complies with Meta Platform Terms.",
    category: "compliance",
    link: "https://developers.facebook.com/terms/",
    required: true,
  },
  {
    id: "facebook_data_deletion",
    title: "Data Deletion Callback",
    description: "Implement data deletion callback URL for GDPR compliance.",
    category: "compliance",
    link: "https://developers.facebook.com/docs/development/create-an-app/app-dashboard/data-deletion-callback",
    required: true,
  },
  {
    id: "facebook_app_review_manage_posts",
    title: "App Review for pages_manage_posts",
    description: "Submit for app review to get pages_manage_posts approved for Advanced Access.",
    category: "compliance",
    link: "https://developers.facebook.com/docs/app-review",
    required: true,
    notes: "⏳ Submit after Request button activates (~24h)",
  },
];

export const facebookCategoryInfo: Record<string, CategoryInfo> = {
  setup: { label: "App Setup", icon: Settings, color: "text-blue-500" },
  permissions: { label: "Permissions", icon: Key, color: "text-purple-500" },
  content: { label: "Content Requirements", icon: Video, color: "text-pink-500" },
  compliance: { label: "Compliance & Review", icon: Shield, color: "text-green-500" },
};
