import { Settings, Key, Image, Shield } from "lucide-react";
import { ChecklistItem, CategoryInfo } from "../types";

export const instagramChecklistItems: ChecklistItem[] = [
  // App Setup
  {
    id: "instagram_facebook_app",
    title: "Instagram via Facebook App",
    description: "Instagram API access is through a Facebook Developer App with Instagram product.",
    category: "setup",
    link: "https://developers.facebook.com/docs/instagram-api/getting-started",
    required: true,
    notes: "✅ Configured in Postora app",
  },
  {
    id: "instagram_business_account",
    title: "Instagram Business/Creator Account Required",
    description: "Users must have Instagram Business or Creator accounts connected to Facebook Pages.",
    category: "setup",
    required: true,
    notes: "✅ Tested with @daressny.kw",
  },
  {
    id: "instagram_product_added",
    title: "Instagram Graph API Product Added",
    description: "Add Instagram Graph API product to your Facebook app.",
    category: "setup",
    link: "https://developers.facebook.com/docs/instagram-api/getting-started",
    required: true,
    notes: "✅ Added to app",
  },
  {
    id: "instagram_redirect_uri",
    title: "OAuth Redirect URI Configured",
    description: "Valid OAuth redirect URI in Facebook app settings for Instagram.",
    category: "setup",
    required: true,
    notes: "✅ Configured",
  },
  {
    id: "instagram_public_profile",
    title: "public_profile Advanced Access",
    description: "Advanced Access for public_profile permission granted by Meta.",
    category: "permissions",
    required: true,
    notes: "✅ Granted — Mar 9, 2026",
  },
  {
    id: "instagram_pages_show_list",
    title: "pages_show_list Advanced Access",
    description: "Advanced Access for pages_show_list permission granted by Meta.",
    category: "permissions",
    required: true,
    notes: "✅ Granted previously",
  },
  // Permissions
  {
    id: "instagram_basic",
    title: "instagram_basic Permission",
    description: "Read basic Instagram account information.",
    category: "permissions",
    required: true,
    notes: "⏳ API test call completed — waiting 24h for Request button activation",
  },
  {
    id: "instagram_content_publish",
    title: "instagram_content_publish Permission",
    description: "Publish content (images, videos, carousels) to Instagram.",
    category: "permissions",
    link: "https://developers.facebook.com/docs/instagram-api/reference/ig-user/media",
    required: true,
    notes: "⏳ API test call completed — waiting 24h for Request button activation",
  },
  {
    id: "instagram_business_manage_comments",
    title: "instagram_business_manage_comments Permission",
    description: "Required for posting first comments on Instagram media via Business Login.",
    category: "permissions",
    link: "https://developers.facebook.com/docs/permissions/reference/instagram_business_manage_comments",
    required: true,
    notes: "⏳ Added to OAuth scopes — needs App Review for Advanced Access",
  },
  {
    id: "instagram_manage_comments",
    title: "instagram_manage_comments Permission",
    description: "Read and manage comments on Instagram content.",
    category: "permissions",
    required: false,
  },
  {
    id: "pages_read_engagement",
    title: "pages_read_engagement Permission",
    description: "Required for accessing Instagram accounts linked to Facebook Pages.",
    category: "permissions",
    required: true,
  },
  // Content Requirements
  {
    id: "instagram_image_specs",
    title: "Image Specifications",
    description: "Images: JPEG format, 1:1 (square), 4:5 (portrait), or 1.91:1 (landscape).",
    category: "content",
    link: "https://developers.facebook.com/docs/instagram-api/reference/ig-user/media",
    required: true,
  },
  {
    id: "instagram_video_specs",
    title: "Video/Reel Specifications",
    description: "Videos: MP4, H.264 codec, 3-60 sec (feed), 3-90 sec (Reels), max 100MB.",
    category: "content",
    required: true,
  },
  {
    id: "instagram_carousel_specs",
    title: "Carousel Support",
    description: "Carousels: 2-10 items, consistent aspect ratio, images or videos.",
    category: "content",
    link: "https://developers.facebook.com/docs/instagram-api/guides/content-publishing#carousel-posts",
    required: true,
  },
  {
    id: "instagram_caption_limits",
    title: "Caption Character Limits",
    description: "Captions support up to 2,200 characters and 30 hashtags.",
    category: "content",
    required: true,
  },
  {
    id: "instagram_account_selection",
    title: "Account Selection UI",
    description: "Allow users to select which Instagram account to post to.",
    category: "content",
    required: true,
  },
  {
    id: "instagram_test_post",
    title: "Successful Test Post from Postora",
    description: "Published a real post to Instagram via Postora to register API calls.",
    category: "content",
    required: true,
    notes: "✅ Published successfully — Mar 9, 2026 (@daressny.kw)",
  },
  // Compliance
  {
    id: "instagram_privacy_policy",
    title: "Privacy Policy URL",
    description: "Privacy policy URL in Facebook app settings.",
    category: "compliance",
    internalLink: "/privacy",
    required: true,
    notes: "✅ Configured",
  },
  {
    id: "instagram_platform_policy",
    title: "Instagram Platform Policy",
    description: "Application complies with Instagram Platform Policy.",
    category: "compliance",
    link: "https://developers.facebook.com/docs/instagram/overview/",
    required: true,
  },
  {
    id: "instagram_app_review_basic",
    title: "App Review for instagram_basic",
    description: "Submit for app review to get instagram_basic approved for Advanced Access.",
    category: "compliance",
    link: "https://developers.facebook.com/docs/app-review/submission-guide",
    required: true,
    notes: "⏳ Submit after Request button activates (~24h)",
  },
  {
    id: "instagram_app_review_publish",
    title: "App Review for instagram_content_publish",
    description: "Submit for app review to get instagram_content_publish approved for Advanced Access.",
    category: "compliance",
    link: "https://developers.facebook.com/docs/app-review/submission-guide",
    required: true,
    notes: "⏳ Submit after Request button activates (~24h)",
  },
  {
    id: "instagram_rate_limits",
    title: "Rate Limit Handling",
    description: "Handle rate limits: 25 posts per 24-hour period per account.",
    category: "compliance",
    required: true,
  },
];

export const instagramCategoryInfo: Record<string, CategoryInfo> = {
  setup: { label: "App Setup", icon: Settings, color: "text-pink-600" },
  permissions: { label: "Permissions", icon: Key, color: "text-purple-500" },
  content: { label: "Content Requirements", icon: Image, color: "text-rose-500" },
  compliance: { label: "Compliance & Review", icon: Shield, color: "text-green-500" },
};
