import { Settings, Key, FileText, Shield } from "lucide-react";
import { ChecklistItem, CategoryInfo } from "../types";

export const twitterChecklistItems: ChecklistItem[] = [
  // App Setup
  {
    id: "twitter_dev_app",
    title: "Twitter Developer App Created",
    description: "Application registered in Twitter/X Developer Portal with appropriate access level.",
    category: "setup",
    link: "https://developer.twitter.com/en/portal/dashboard",
    required: true,
  },
  {
    id: "twitter_api_keys",
    title: "API Keys Configured",
    description: "API Key (Consumer Key) and API Secret stored securely in environment variables.",
    category: "setup",
    required: true,
  },
  {
    id: "twitter_access_tokens",
    title: "Access Token and Secret Configured",
    description: "Access Token and Access Token Secret generated and stored for user authentication.",
    category: "setup",
    required: true,
  },
  {
    id: "twitter_oauth_callback",
    title: "OAuth Callback URL Configured",
    description: "Callback URL added in app settings (must match exactly).",
    category: "setup",
    required: true,
  },
  {
    id: "twitter_app_permissions",
    title: "App Permissions Set to Read and Write",
    description: "Update app permissions from Read-only to Read and Write in User Authentication Settings.",
    category: "setup",
    link: "https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens",
    required: true,
  },
  // Scopes & Permissions
  {
    id: "twitter_oauth2_scopes",
    title: "OAuth 2.0 Scopes (if using OAuth 2.0)",
    description: "Configure required scopes: tweet.read, tweet.write, users.read, offline.access.",
    category: "scopes",
    link: "https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code",
    required: false,
  },
  {
    id: "twitter_oauth1_setup",
    title: "OAuth 1.0a Configuration",
    description: "Properly implement OAuth 1.0a signature generation for API requests.",
    category: "scopes",
    required: true,
  },
  {
    id: "twitter_elevated_access",
    title: "Elevated Access (if needed)",
    description: "Apply for Elevated access for higher rate limits and additional endpoints.",
    category: "scopes",
    link: "https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api",
    required: false,
  },
  {
    id: "twitter_media_upload",
    title: "Media Upload Permission",
    description: "Ensure media upload capabilities are enabled for posting images/videos.",
    category: "scopes",
    link: "https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/overview",
    required: true,
  },
  // Content Requirements
  {
    id: "twitter_text_limits",
    title: "Text Character Limits",
    description: "Tweets limited to 280 characters (or 25,000 for X Premium subscribers).",
    category: "content",
    required: true,
  },
  {
    id: "twitter_image_specs",
    title: "Image Specifications",
    description: "Images: JPEG, PNG, GIF, WEBP. Max 5MB for images, 15MB for GIFs.",
    category: "content",
    link: "https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices",
    required: true,
  },
  {
    id: "twitter_video_specs",
    title: "Video Specifications",
    description: "Videos: MP4 or MOV, max 512MB, up to 2:20 duration, H.264 codec.",
    category: "content",
    required: true,
  },
  {
    id: "twitter_thread_support",
    title: "Thread Support",
    description: "Implement tweet threading using reply_to_tweet_id parameter.",
    category: "content",
    required: false,
  },
  {
    id: "twitter_poll_support",
    title: "Poll Support (Optional)",
    description: "Support for creating polls with up to 4 options.",
    category: "content",
    link: "https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets",
    required: false,
  },
  // Compliance & Rate Limits
  {
    id: "twitter_developer_agreement",
    title: "Developer Agreement Compliance",
    description: "Application complies with Twitter Developer Agreement and Policy.",
    category: "compliance",
    link: "https://developer.twitter.com/en/developer-terms/agreement-and-policy",
    required: true,
  },
  {
    id: "twitter_automation_rules",
    title: "Automation Rules Compliance",
    description: "Follow Twitter's automation rules - no spam, no duplicate content.",
    category: "compliance",
    link: "https://help.twitter.com/en/rules-and-policies/twitter-automation",
    required: true,
  },
  {
    id: "twitter_rate_limits",
    title: "Rate Limit Handling",
    description: "Handle rate limits: 200 tweets/15 min (user), 300 tweets/3 hours (app).",
    category: "compliance",
    link: "https://developer.twitter.com/en/docs/twitter-api/rate-limits",
    required: true,
  },
  {
    id: "twitter_brand_guidelines",
    title: "Twitter/X Brand Guidelines",
    description: "Follow brand guidelines for buttons, logos, and display names.",
    category: "compliance",
    link: "https://about.twitter.com/en/who-we-are/brand-toolkit",
    required: false,
  },
  {
    id: "twitter_display_requirements",
    title: "Display Requirements",
    description: "Follow Twitter display requirements when showing tweets in your app.",
    category: "compliance",
    link: "https://developer.twitter.com/en/developer-terms/display-requirements",
    required: true,
  },
  {
    id: "twitter_privacy_policy",
    title: "Privacy Policy URL",
    description: "Privacy policy URL added to Twitter developer app settings.",
    category: "compliance",
    internalLink: "/privacy",
    required: true,
  },
  {
    id: "twitter_tos_url",
    title: "Terms of Service URL",
    description: "Terms of service URL configured in app settings.",
    category: "compliance",
    internalLink: "/terms",
    required: true,
  },
];

export const twitterCategoryInfo: Record<string, CategoryInfo> = {
  setup: { label: "App Setup", icon: Settings, color: "text-sky-500" },
  scopes: { label: "Scopes & Permissions", icon: Key, color: "text-purple-500" },
  content: { label: "Content Requirements", icon: FileText, color: "text-blue-500" },
  compliance: { label: "Compliance & Rate Limits", icon: Shield, color: "text-green-500" },
};
